# Use postgres/example user/password credentials
version: '3.9'

services:

  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=crm_db
      - POSTGRES_USER=crm_db_user
      - POSTGRES_PASSWORD=changeme
    ports:
      - "5432:5432"